name: CD

on:
  push:
    branches: [master]
  workflow_dispatch:

env:
  SISTEMA: sigep

jobs:
  deploy:
    name: executar deploy no servidor linux
    runs-on: self-hosted
    steps:
      - name: executar script de deploy dentro do servidor
        run: |
          /root/scripts/sigep-deploy.sh master